services:
  db:
    image: postgres:16
    container_name: shorty-db
    environment:
      POSTGRES_DB: shorty
      POSTGRES_USER: shorty
      POSTGRES_PASSWORD: shorty
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  app:
    build: .
    container_name: shorty-app
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/shorty
      SPRING_DATASOURCE_USERNAME: shorty
      SPRING_DATASOURCE_PASSWORD: shorty
      SPRING_JPA_HIBERNATE_DDL_AUTO: validate
      SPRING_PROFILES_ACTIVE: prod
    ports:
      - "8080:8080"

volumes:
  pgdata:
