spring:
  profiles:
    active: dev

  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
    properties:
      hibernate.format_sql: true
      hibernate.show_sql: false

flyway:
  enabled: true
  locations: classpath:db/migration

server:
  port: 8080
