spring:
  datasource:
    url: jdbc:h2:mem:shorty;MODE=PostgreSQL;DB_CLOSE_DELAY=-1;DATABASE_TO_UPPER=false
    username: sa
    password:
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: validate

  h2:
    console:
      enabled: true
      path: /h2-console
