-- V2__add_clicks_table.sql
-- Idempotent creation in case table already exists
CREATE TABLE IF NOT EXISTS clicks (
                                      id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                      link_id UUID NOT NULL,
                                      ts TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
                                      ip_hash CHAR(64) NOT NULL,
    user_agent TEXT,
    referrer TEXT
    );

-- Add FK separately (IF NOT EXISTS not supported for constraints across DBs)
-- This block tries to add FK and ignores error if it already exists (works fine in Postgres/H2 dev)
ALTER TABLE clicks
    ADD CONSTRAINT fk_clicks_link
        FOREIGN KEY (link_id) REFERENCES links(id) ON DELETE CASCADE;

-- Helpful indexes (idempotent for H2/Postgres)
CREATE INDEX IF NOT EXISTS idx_clicks_link_ts ON clicks(link_id, ts DESC);
CREATE INDEX IF NOT EXISTS idx_clicks_referrer ON clicks(referrer);
